qq = (input('Digite algo qualquer: '))
print('O tipo da palavra digitado é', type(qq))
print('O valor dela são digitos?', qq.isdigit())
print('O valor dela são númericos?', qq.isnumeric())
print('O valor dela são letras?', qq.isalpha())
print('O valor dela são alfanúmericos?', qq.isalnum())
print('O valor dela são apenas espaços?', qq.isspace())
print('O valor dela são maiúsculas?', qq.isupper())
print('O valor dela são minusclas?', qq.islower())

